import type { Scorecard, CategoryScore } from '../types/output.js';
import type { Finding } from '../types/findings.js';
import type { InvestigationEntry, FetchedDoc } from '../types/state.js';

/**
 * Render a scorecard + agent-written sections into a consultant-readable markdown brief.
 */
export function renderBrief(
  scorecard: Scorecard,
  sections: Record<string, string>,
  investigationLog: InvestigationEntry[],
  fetchedDocs: FetchedDoc[],
  toolCallsUsed: number,
  toolCallBudget: number,
): string {
  const lines: string[] = [];

  lines.push(`# Project ${briefTitle(scorecard.goalType)}: ${scorecard.repoName}`);
  lines.push('');
  lines.push(`> Generated by **repo-audit-delivery-agent** | ${new Date(scorecard.generatedAt).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`);
  lines.push('');
  lines.push(`**Goal:** ${scorecard.goalType} | **Overall score:** ${scoreEmoji(scorecard.overallScore)} ${scorecard.overallScore.toUpperCase()}`);
  lines.push(`**Investigation:** ${toolCallsUsed} tool calls | **Findings:** ${scorecard.topRisks.length > 0 ? scorecard.topRisks.length + ' risks identified' : 'no risks'}`);
  lines.push('');
  lines.push('---');
  lines.push('');

  // Render agent-written sections
  // Normalize keys: the LLM may use slightly different key names
  const normalizedSections = normalizeSectionKeys(sections);

  const sectionOrder = [
    'project_overview',
    'stack_and_architecture',
    'key_files',
    'cms_integration',
    'preview_editing',
    'configuration_environment',
    'local_setup',
    // scorecard and top_risks are EXCLUDED here — the renderer appends
    // authoritative computed versions below. Including LLM-written ones
    // causes duplication and contradictions (LLM may score differently).
    'first_week_reading',
    'client_questions',
    'next_actions',
    // Audit/migration sections
    'migration_hotspots',
    'migration_order',
    'component_inventory',
  ];

  // Skip LLM-written scorecard/risks — computed versions are appended below
  const skipSections = new Set(['scorecard', 'top_risks']);

  const rendered = new Set<string>();
  for (const key of sectionOrder) {
    if (normalizedSections[key]) {
      lines.push(normalizedSections[key]);
      lines.push('');
      rendered.add(key);
    }
  }

  // Any sections not in the predefined order (but still skip scorecard/risks)
  for (const [key, content] of Object.entries(normalizedSections)) {
    if (!rendered.has(key) && !skipSections.has(key) && content) {
      lines.push(content);
      lines.push('');
    }
  }

  // Architecture scorecard (always rendered from computed data)
  lines.push('## Architecture Scorecard');
  lines.push('');
  lines.push(`**Overall: ${scoreEmoji(scorecard.overallScore)} ${scorecard.overallScore.toUpperCase()}**`);
  lines.push('');
  lines.push('| Category | Score | Findings | Summary |');
  lines.push('|----------|-------|----------|---------|');
  for (const cat of scorecard.categories) {
    lines.push(
      `| ${categoryDisplayName(cat)} | ${scoreEmoji(cat.score)} ${cat.score} | ${cat.findings.length} | ${cat.summary} |`,
    );
  }
  lines.push('');

  // Top risks
  if (scorecard.topRisks.length > 0) {
    lines.push('## Top Risks');
    lines.push('');
    for (let i = 0; i < scorecard.topRisks.length; i++) {
      const risk = scorecard.topRisks[i];
      lines.push(`### ${i + 1}. ${risk.title}`);
      lines.push(`**Severity:** ${risk.severity} | **Category:** ${risk.category}`);
      lines.push('');
      lines.push(risk.description);
      if (risk.evidence.length > 0) {
        lines.push('');
        for (const ev of risk.evidence) {
          lines.push(`- \`${ev.filePath}\`${ev.lineNumber ? `:${ev.lineNumber}` : ''}: ${ev.description}`);
        }
      }
      lines.push('');
    }
  }

  // Documentation sources
  if (fetchedDocs.length > 0) {
    lines.push('---');
    lines.push('');
    lines.push('## Documentation Sources');
    lines.push('');
    for (const doc of fetchedDocs) {
      lines.push(`- [${doc.title}](${doc.url}) — used in findings: ${doc.usedInFindings.join(', ') || 'general context'}`);
    }
    lines.push('');
  }

  // Investigation log — compact summary, not raw JSON
  if (investigationLog.length > 0) {
    lines.push('---');
    lines.push('');
    lines.push('## Investigation Log');
    lines.push('');
    lines.push('| Step | Action | Reasoning |');
    lines.push('|------|--------|-----------|');
    for (const entry of investigationLog) {
      const reasoning = entry.reasoning?.replace(/\|/g, '\\|').replace(/\n/g, ' ').trim() || '—';
      lines.push(`| ${entry.step} | \`${entry.action}\` | ${reasoning} |`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Normalize LLM-provided section keys to the expected canonical keys.
 * Handles common variations like key_files_table → key_files,
 * environment_and_configuration → configuration_environment, etc.
 */
function normalizeSectionKeys(sections: Record<string, string>): Record<string, string> {
  const KEY_ALIASES: Record<string, string> = {
    // key_files variants
    key_files_table: 'key_files',
    key_files_and_directories: 'key_files',
    important_files: 'key_files',
    // configuration variants
    environment_and_configuration: 'configuration_environment',
    environment_configuration: 'configuration_environment',
    config_environment: 'configuration_environment',
    environment: 'configuration_environment',
    configuration: 'configuration_environment',
    // local setup variants
    local_setup_steps: 'local_setup',
    local_development: 'local_setup',
    local_dev_setup: 'local_setup',
    getting_started: 'local_setup',
    // scorecard variants
    architecture_scorecard: 'scorecard',
    // top risks variants
    top_5_risks: 'top_risks',
    risks: 'top_risks',
    risk_summary: 'top_risks',
    // reading list variants
    first_week_reading_list: 'first_week_reading',
    reading_list: 'first_week_reading',
    // questions variants
    questions_for_client: 'client_questions',
    open_questions: 'client_questions',
    questions: 'client_questions',
    // next actions variants
    suggested_next_actions: 'next_actions',
    recommendations: 'next_actions',
    next_steps: 'next_actions',
    // preview variants
    preview_and_editing: 'preview_editing',
    editing: 'preview_editing',
    // CMS variants
    cms: 'cms_integration',
    // overview variants
    overview: 'project_overview',
    // stack variants
    stack: 'stack_and_architecture',
    architecture: 'stack_and_architecture',
  };

  const result: Record<string, string> = {};
  for (const [key, content] of Object.entries(sections)) {
    const normalizedKey = KEY_ALIASES[key] ?? key;
    // Don't overwrite if canonical key already exists
    if (!result[normalizedKey]) {
      result[normalizedKey] = content;
    }
  }
  return result;
}

function briefTitle(goalType: string): string {
  switch (goalType) {
    case 'onboarding': return 'Onboarding Brief';
    case 'audit': return 'Architecture Audit';
    case 'migration': return 'Migration Scout Report';
    case 'component-map': return 'Component Map';
    case 'ci-check': return 'CI Health Check';
    default: return 'Analysis Report';
  }
}

function scoreEmoji(score: string): string {
  switch (score) {
    case 'red': return '🔴';
    case 'yellow': return '🟡';
    case 'green': return '🟢';
    default: return '⚪';
  }
}

function categoryDisplayName(cat: CategoryScore): string {
  // Map category codes back to display names
  const map: Record<string, string> = {
    stack: 'Stack & Framework',
    nextjs: 'Stack & Framework',
    'cms-integration': 'CMS Integration',
    'preview-editing': 'Preview & Editing',
    security: 'Security & Configuration',
    configuration: 'Security & Configuration',
    architecture: 'Architecture',
    routing: 'Architecture',
    'data-fetching': 'Architecture',
    dependencies: 'Dependencies',
    deployment: 'Deployment',
  };
  return map[cat.category] ?? cat.category;
}
