import type { Scorecard, ScoreLevel, CategoryScore } from '../types/output.js';
import type { Finding, Severity } from '../types/findings.js';

export interface ComparisonInput {
  repoName: string;
  scorecard: Scorecard;
  findings: Finding[];
  briefMarkdown: string;
}

/**
 * Render a side-by-side comparison report for two repository audits.
 * Deterministic / template-driven — no LLM involved.
 */
export function renderComparison(repoA: ComparisonInput, repoB: ComparisonInput): string {
  const lines: string[] = [];

  // Header
  lines.push(`# Comparison Report: ${repoA.repoName} vs ${repoB.repoName}`);
  lines.push('');
  lines.push(
    `> Generated by **repo-audit-delivery-agent** | ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`,
  );
  lines.push('');
  lines.push('---');
  lines.push('');

  // Overall scores
  lines.push('## Overall Scores');
  lines.push('');
  lines.push('| Repo | Overall Score |');
  lines.push('|------|---------------|');
  lines.push(
    `| ${repoA.repoName} | ${scoreEmoji(repoA.scorecard.overallScore)} ${repoA.scorecard.overallScore.toUpperCase()} |`,
  );
  lines.push(
    `| ${repoB.repoName} | ${scoreEmoji(repoB.scorecard.overallScore)} ${repoB.scorecard.overallScore.toUpperCase()} |`,
  );
  lines.push('');

  // Side-by-side scorecard table
  lines.push('## Scorecard Comparison');
  lines.push('');
  lines.push(`| Category | ${repoA.repoName} | ${repoB.repoName} | Delta |`);
  lines.push('|----------|' + '-'.repeat(repoA.repoName.length + 2) + '|' + '-'.repeat(repoB.repoName.length + 2) + '|-------|');

  // Build maps for category lookups
  const catMapA = buildCategoryMap(repoA.scorecard.categories);
  const catMapB = buildCategoryMap(repoB.scorecard.categories);
  const allCategories = new Set([...catMapA.keys(), ...catMapB.keys()]);

  for (const cat of allCategories) {
    const scoreA = catMapA.get(cat);
    const scoreB = catMapB.get(cat);
    const displayA = scoreA ? `${scoreEmoji(scoreA.score)} ${scoreA.score}` : '— n/a';
    const displayB = scoreB ? `${scoreEmoji(scoreB.score)} ${scoreB.score}` : '— n/a';
    const delta = computeDelta(scoreA?.score, scoreB?.score);
    lines.push(`| ${cat} | ${displayA} | ${displayB} | ${delta} |`);
  }
  lines.push('');

  // Key Differences — categories where scores differ
  const differences: { category: string; scoreA?: ScoreLevel; scoreB?: ScoreLevel }[] = [];
  const commonPatterns: { category: string; score: ScoreLevel }[] = [];

  for (const cat of allCategories) {
    const scoreA = catMapA.get(cat)?.score;
    const scoreB = catMapB.get(cat)?.score;

    if (scoreA && scoreB && scoreA === scoreB) {
      commonPatterns.push({ category: cat, score: scoreA });
    } else {
      differences.push({ category: cat, scoreA, scoreB });
    }
  }

  lines.push('## Key Differences');
  lines.push('');
  if (differences.length === 0) {
    lines.push('No differences — both repositories scored identically across all categories.');
  } else {
    for (const diff of differences) {
      const a = diff.scoreA ? `${scoreEmoji(diff.scoreA)} ${diff.scoreA}` : 'n/a';
      const b = diff.scoreB ? `${scoreEmoji(diff.scoreB)} ${diff.scoreB}` : 'n/a';
      lines.push(`- **${diff.category}**: ${repoA.repoName} ${a} / ${repoB.repoName} ${b}`);
    }
  }
  lines.push('');

  // Common Patterns — categories where scores match
  lines.push('## Common Patterns');
  lines.push('');
  if (commonPatterns.length === 0) {
    lines.push('No common patterns — all categories differ between repositories.');
  } else {
    for (const pat of commonPatterns) {
      lines.push(`- **${pat.category}**: Both ${scoreEmoji(pat.score)} ${pat.score}`);
    }
  }
  lines.push('');

  // Finding count comparison by severity
  lines.push('## Finding Count by Severity');
  lines.push('');
  const severities: Severity[] = ['critical', 'high', 'medium', 'low', 'info'];
  const countsA = countBySeverity(repoA.findings);
  const countsB = countBySeverity(repoB.findings);

  lines.push(`| Severity | ${repoA.repoName} | ${repoB.repoName} |`);
  lines.push('|----------|' + '-'.repeat(repoA.repoName.length + 2) + '|' + '-'.repeat(repoB.repoName.length + 2) + '|');
  for (const sev of severities) {
    lines.push(`| ${sev} | ${countsA[sev]} | ${countsB[sev]} |`);
  }
  lines.push(`| **Total** | **${repoA.findings.length}** | **${repoB.findings.length}** |`);
  lines.push('');

  return lines.join('\n');
}

// --- Helpers ---

const SCORE_NUMERIC: Record<ScoreLevel, number> = {
  green: 3,
  yellow: 2,
  red: 1,
};

function scoreEmoji(score: ScoreLevel): string {
  switch (score) {
    case 'red': return '🔴';
    case 'yellow': return '🟡';
    case 'green': return '🟢';
    default: return '⚪';
  }
}

function buildCategoryMap(categories: CategoryScore[]): Map<string, CategoryScore> {
  const DISPLAY_NAMES: Record<string, string> = {
    stack: 'Stack & Framework',
    nextjs: 'Stack & Framework',
    'cms-integration': 'CMS Integration',
    'preview-editing': 'Preview & Editing',
    security: 'Security & Configuration',
    configuration: 'Security & Configuration',
    architecture: 'Architecture',
    routing: 'Architecture',
    'data-fetching': 'Architecture',
    dependencies: 'Dependencies',
    deployment: 'Deployment',
  };

  const map = new Map<string, CategoryScore>();
  for (const cat of categories) {
    const displayName = DISPLAY_NAMES[cat.category] ?? cat.category;
    // First entry wins (avoids duplicates from multiple finding categories mapping to same display)
    if (!map.has(displayName)) {
      map.set(displayName, cat);
    }
  }
  return map;
}

function computeDelta(scoreA?: ScoreLevel, scoreB?: ScoreLevel): string {
  if (!scoreA || !scoreB) return '—';
  if (scoreA === scoreB) return '=';

  const numA = SCORE_NUMERIC[scoreA];
  const numB = SCORE_NUMERIC[scoreB];
  const diff = numB - numA;

  if (diff > 0) return `+${diff} (B better)`;
  return `${diff} (A better)`;
}

function countBySeverity(findings: Finding[]): Record<Severity, number> {
  const counts: Record<Severity, number> = {
    critical: 0,
    high: 0,
    medium: 0,
    low: 0,
    info: 0,
  };
  for (const f of findings) {
    counts[f.severity]++;
  }
  return counts;
}
