/**
 * Cross-goal summary renderer for universal investigation.
 * Produces a matrix comparing all 8 goal scorecards from the same findings pool.
 */

import type { Scorecard, ScoreLevel } from '../types/output.js';
import type { Finding } from '../types/findings.js';
import type { GoalType } from '../types/state.js';

export interface MultiGoalResult {
  goal: GoalType;
  scorecard: Scorecard;
  briefPath?: string;
  error?: string;
}

export interface PassBreakdown {
  pass: string;
  toolCalls: number;
  durationMs: number;
}

export interface MultiGoalMetrics {
  totalToolCalls: number;
  totalDurationMs: number;
  totalCostUsd: number;
  passBreakdown: PassBreakdown[];
}

export function renderMultiGoalSummary(
  repoName: string,
  results: MultiGoalResult[],
  findings: Finding[],
  metrics: MultiGoalMetrics,
): string {
  const lines: string[] = [];

  lines.push(`# Universal Analysis: ${repoName}`);
  lines.push('');
  lines.push(
    `> Generated by **repo-audit-delivery-agent** | ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`,
  );
  lines.push('');
  lines.push(`**Mode:** Universal (all goals) | **Findings:** ${findings.length} total`);
  lines.push(
    `**Tool calls:** ${metrics.totalToolCalls} | **Duration:** ${(metrics.totalDurationMs / 1000).toFixed(1)}s | **Est. cost:** $${metrics.totalCostUsd.toFixed(4)}`,
  );
  lines.push('');

  // Pass breakdown
  lines.push('### Investigation Passes');
  lines.push('');
  lines.push('| Pass | Tool Calls | Duration |');
  lines.push('|------|-----------|----------|');
  for (const pass of metrics.passBreakdown) {
    lines.push(`| ${pass.pass} | ${pass.toolCalls} | ${(pass.durationMs / 1000).toFixed(1)}s |`);
  }
  lines.push('');

  // Score matrix
  lines.push('---');
  lines.push('');
  lines.push('## Score Matrix');
  lines.push('');
  lines.push('| Goal | Overall | Categories |');
  lines.push('|------|---------|------------|');
  for (const result of results) {
    const emoji = scoreEmoji(result.scorecard.overallScore);
    const catSummary = result.scorecard.categories
      .map((c) => `${scoreEmoji(c.score)} ${c.category}`)
      .join(', ');
    const errorNote = result.error ? ` (partial: ${result.error})` : '';
    lines.push(
      `| ${result.goal} | ${emoji} ${result.scorecard.overallScore.toUpperCase()}${errorNote} | ${catSummary} |`,
    );
  }
  lines.push('');

  // Per-goal scorecards
  lines.push('## Per-Goal Scorecards');
  lines.push('');
  for (const result of results) {
    lines.push(
      `### ${goalDisplayName(result.goal)} — ${scoreEmoji(result.scorecard.overallScore)} ${result.scorecard.overallScore.toUpperCase()}`,
    );
    lines.push('');
    lines.push('| Category | Score | Findings |');
    lines.push('|----------|-------|----------|');
    for (const cat of result.scorecard.categories) {
      lines.push(`| ${cat.category} | ${scoreEmoji(cat.score)} ${cat.score} | ${cat.findings.length} |`);
    }
    lines.push('');
    if (result.briefPath) {
      lines.push(`Brief: [${result.goal}](${result.briefPath})`);
      lines.push('');
    }
  }

  // Unified top risks
  const allRisks = results.flatMap((r) => r.scorecard.topRisks);
  const seen = new Set<string>();
  const uniqueRisks: Finding[] = [];
  for (const risk of allRisks) {
    if (!seen.has(risk.id)) {
      seen.add(risk.id);
      uniqueRisks.push(risk);
    }
  }
  const SEVERITY_ORDER: Record<string, number> = { critical: 5, high: 4, medium: 3, low: 2, info: 1 };
  const topRisks = uniqueRisks
    .sort((a, b) => (SEVERITY_ORDER[b.severity] ?? 0) - (SEVERITY_ORDER[a.severity] ?? 0))
    .slice(0, 10);

  if (topRisks.length > 0) {
    lines.push('---');
    lines.push('');
    lines.push('## Top Risks (Unified)');
    lines.push('');
    for (let i = 0; i < topRisks.length; i++) {
      const risk = topRisks[i];
      const desc =
        risk.description.length > 150
          ? risk.description.slice(0, 150) + '...'
          : risk.description;
      lines.push(
        `${i + 1}. **${risk.title}** (${risk.severity}, ${risk.category}) — ${desc}`,
      );
    }
    lines.push('');
  }

  // Finding distribution
  lines.push('---');
  lines.push('');
  lines.push('## Finding Distribution');
  lines.push('');
  const byCat = new Map<string, number>();
  const bySev = new Map<string, number>();
  for (const f of findings) {
    byCat.set(f.category, (byCat.get(f.category) ?? 0) + 1);
    bySev.set(f.severity, (bySev.get(f.severity) ?? 0) + 1);
  }
  lines.push('**By category:**');
  for (const [cat, count] of [...byCat.entries()].sort((a, b) => b[1] - a[1])) {
    lines.push(`- ${cat}: ${count}`);
  }
  lines.push('');
  lines.push('**By severity:**');
  for (const sev of ['critical', 'high', 'medium', 'low', 'info']) {
    const count = bySev.get(sev) ?? 0;
    if (count > 0) lines.push(`- ${sev}: ${count}`);
  }
  lines.push('');

  return lines.join('\n');
}

export function scoreEmoji(score: ScoreLevel | string): string {
  switch (score) {
    case 'red': return '🔴';
    case 'yellow': return '🟡';
    case 'green': return '🟢';
    default: return '⚪';
  }
}

export function goalDisplayName(goal: string): string {
  const names: Record<string, string> = {
    onboarding: 'Onboarding Brief',
    audit: 'Architecture Audit',
    migration: 'Migration Scout',
    'component-map': 'Component Map',
    'ci-check': 'CI Health Check',
    'security-review': 'Security Review',
    nextjs: 'Next.js Audit',
    accessibility: 'Accessibility Audit',
  };
  return names[goal] ?? goal;
}
